apiVersion: v1
kind: Secret
metadata:
  name: food-challenge-secrets
  namespace: fiap-tech-challenge
type: Opaque
data:
  ConnectionStrings__DbConnection: SG9zdD1wb3N0Z3JlcztQb3J0PTU0MzI7RGF0YWJhc2U9Zm9vZGNoYWxsZW5nZV9kYjtVc2VybmFtZT1yb290O1Bhc3N3b3JkPTJGMnVNN1N4c0NrUmR5RVY2REtw
