services:
  foodchallenge_mongo_db:
    image: mongo:7
    container_name: foodchallenge_mongo_db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 3s
      retries: 10
    ports:
      - "27017:27017"
    volumes:
      - foodchallenge_mongo_data:/data/db
    networks:
      - foodchallenge_network

  foodchallenge_payment_api:
    image: foodchallenge/payment-api
    container_name: foodchallenge_payment_api
    build:
      context: ../../src/FoodChallenge.Payment
      dockerfile: ../../tools/docker/build/dotnet.web-api.Dockerfile
      target: final
    environment:
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT}
      ASPNETCORE_URLS: "http://+:5002"
      MongoDb__ConnectionString: ${MongoDb__ConnectionString}
      MongoDb__DatabaseName: ${MONGO_DATABASE}
      MercadoPago__BaseUrl: ${MercadoPago__BaseUrl}
      MercadoPago__AccessToken: ${MercadoPago__AccessToken}
      MercadoPago__UserId: ${MercadoPago__UserId}
      MercadoPago__CaixaCodigo: ${MercadoPago__CaixaCodigo}
      OAuth__Authority: ${OAuth__Authority}
    depends_on:
      foodchallenge_mongo_db:
        condition: service_healthy
    networks:
      - foodchallenge_network
    ports:
      - "5002:5002"

volumes:
  foodchallenge_mongo_data:
    driver: local

networks:
  foodchallenge_network:
    external: true
    name: fiap_foodchallenge_network
